### ISSUE TITLE
Add monitor description to failed monitors metric

### ISSUE THREAD

**Issue by dominikmaeckel** [tudo-aqua/stars#21]

**Comment by tillschallau** [comment]
Can you clarify what the issue is? In the current main branch there is documentation available for the FailedMonitorsMetric. 

https://github.com/tudo-aqua/stars/blob/c4f438d1b7f03968bf92ab07becad90ce6dbed7f/stars-core/src/main/kotlin/tools/aqua/stars/core/metric/metrics/postEvaluation/FailedMonitorsMetric.kt#L30-L42

I would agree that the documentation could be more elaborate.

**Comment by tillschallau** [comment]
After discussion: A generic description of the monitor was added. 
A more fitting documentation should be created.
